### ISSUE TITLE
Logo too big when make app window smaller

### ISSUE THREAD

**Issue by leppott** [Blocktt/KDHEtools#11]
When resize the app window smaller than full size (or even smaller monitors) the KS logo is too big and overlaps the main section.

![image](https://github.com/Blocktt/KDHEtools/assets/24276278/7bb89574-00f0-4707-b41f-9094743c6754)

The image size is set to 200 in external/tab_Background.R

![image](https://github.com/Blocktt/KDHEtools/assets/24276278/d8d2eb31-192a-4b40-8ab3-8942b0990a73)

**Comment by leppott** [comment]
Change from pixel size (200) to relative size using "width" and "100%" (of the available space, that is, the sidebar).

![image](https://github.com/Blocktt/KDHEtools/assets/24276278/b7ef2ac0-c977-4089-9a59-4859cc152437)

**Full Size**
![image](https://github.com/Blocktt/KDHEtools/assets/24276278/aab8d0fc-2444-4b36-bab5-7c95541d8ea1)


**Windowed (smaller) Size**
![image](https://github.com/Blocktt/KDHEtools/assets/24276278/7bdbe1ab-a106-4ca2-af79-3e2e652715fb)

**Comment by Blocktt** [comment]
Solved with Erik's v0.1.2.9043 edits.

**Comment by leppott** [comment]
Looks like I only did the fix for the tab ("background")  in the Black bar at the top.  

Still have the issue for the other 3 tabs (Prepare Data, Calculate MMI, and Troubleshooting).

![image](https://github.com/Blocktt/KDHEtools/assets/24276278/164424a3-60da-4d5a-9d39-07d8a95cfee6)

![image](https://github.com/Blocktt/KDHEtools/assets/24276278/eea05f6d-80d1-4a81-a9f7-7bb0226fdcdb)

**Comment by Blocktt** [comment]
Resolved in [v0.1.2.9063](https://github.com/Blocktt/KDHEtools/commit/e45f936573ff05e9e93c1d8f39675ad98548f0dd)
